"""create schools table

Revision ID: 213a666fcf19
Revises: 
Create Date: 2026-08-01 07:33:17.106342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213a666fcf19'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=12), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('motto', sa.String(length=200), nullable=True),
    sa.Column('admin_name', sa.String(length=150), nullable=False),
    sa.Column('admin_email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_admin_email'), 'schools', ['admin_email'], unique=True)
    op.create_index(op.f('ix_schools_code'), 'schools', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schools_code'), table_name='schools')
    op.drop_index(op.f('ix_schools_admin_email'), table_name='schools')
    op.drop_table('schools')
    # ### end Alembic commands ###
